
PartyMassWorkListView

通过ListView内嵌ViewPager和GrideView避免了滑动冲突问题，且实现了三个控件的整体滑动效果。在实现ViewPager的嵌入过程中出现了页面可以正常滑动，监听器也正常但Viewpager
下方指示器文字与指示点不刷新的问题，经过一番查看发现只有当ListView进行上下滑动之后ViewPager指示器才会刷新，通过一天时间的讨论与纠结终于陈宫解决了该问题。
问题在于ViewPager的Adapter与pageListenner在getView中进行了多次初始化，而我们只需在必要时进行一次初始化即可，因此可以将其移动至convertView为null时进行的操作中即可，
另一个问题在于onPageSelected方法中设置好指示器显示内容后需通过notifyDataSetInvalidated（）方法进行页面重绘，修改好这两点问题之后一切就都正常了。

PartyMassWorkViewPagerGrideViewListView

采用ViewPager，GrideView和listView三个控件实现某UI界面设计，但在最终完成整体滑动效果时（在其外层加入了一个ScrollView）出现了滑动冲突问题，
其中各控件独立滑动，且ListView和GrideView分别显示不全，通过重写ListView与GrideView的onMeasure方法设定固定绘制大小后虽解决了显示不全的问题，
但依旧无法实现整体滑动效果，在此期间尝试了自定义ScrollView进行外部拦截，避免滑动冲突，依旧无效。最终经高手指点通过ListView内嵌ViewPager和
GrideView实现整体滑动效果，通过点击事件传递机制来响应GrideView与ViewPager的点击与滑动，成功解决难题。在此对某高手表示感谢！
